# remote_theme: pages-themes/cayman@v0.2.0
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: 44th Velian Legionnaires
description: You've come to the home of the finest Colonial regiment, the 44th Velian Legionnaires!
url: https://44th.cc
logo: "/assets/images/44th.png"